=== PGeorgieva199/Rentgen/Roentgen_6-Sept-2023/etc/image_infos.dtd
<!ELEMENT image_infos (config+)>

<!ELEMENT config (name, window?, image?, elt+)>
<!ATTLIST config
  showorientation (0|1) "1">

<!ELEMENT name (#PCDATA)>
<!ELEMENT window (font?, block+)>
<!ELEMENT image (font?, block+)>

<!ELEMENT font EMPTY>
<!ATTLIST font
  charset			CDATA "0"
  clipprecision		CDATA "2"
  escapement		CDATA "0"
  facename			CDATA "MS Sans Serif"
  height			CDATA "-8"
  italic			CDATA "0"
  orientation		CDATA "0"
  outprecision		CDATA "1"
  pitchandfamily	CDATA "34"
  quality			CDATA "1"
  strikeout			CDATA "0"
  underline			CDATA "0"
  weight			CDATA "400"
  width				CDATA "0"
  red				CDATA "255"
  green				CDATA "255"
  blue				CDATA "255">

<!ELEMENT block (font?, line*)>
<!ATTLIST block
  type		(text|tag|calliper|localizer|ownerdrawn)	"text"
  hotspot	(NW|N|NE|W|C|E|SW|S|SE)		#REQUIRED
  xpos		CDATA						#REQUIRED
  xunit		(PERCENT|PIXEL)				"PERCENT"
  ypos		CDATA						#REQUIRED
  yunit		(PERCENT|PIXEL)				"PERCENT"
  justification (L|C|R)					#REQUIRED>

<!ELEMENT line (token*)>
<!ATTLIST line
  blank     (0|1)		"0">

<!ELEMENT token (#PCDATA)>
<!ATTLIST token
  id	CDATA #IMPLIED>

<!ELEMENT elt (#PCDATA)>
<!ATTLIST elt
  id		CDATA #REQUIRED
  select	(0|1) "1">

=== PGeorgieva199/Rentgen/Roentgen_6-Sept-2023/etc/image_infos.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE image_infos SYSTEM "image_infos.dtd">

<image_infos>

	<config>
		<name>Default</name>

		<image>

		<font charset="0" clipprecision="2" escapement="0" 
			italic="0" orientation="0" outprecision="1"
			pitchandfamily="34" quality="1" strikeout="0" underline="0"
			facename="Arial"
			height="-12" weight="400"/>

		<block hotspot="NW"
			   xpos="0" xunit="PERCENT"
			   ypos="0" yunit="PERCENT"
			   justification="L">
			<name>Patient, Study Information</name>
			<line>
				<token id="1.1">$IoNfamilyName$  $IoNfirstName$</token>
			</line>
			<line>
				<token id="1.2">$VarPatientAge$</token>
				<token id="1.3">$[ ]IoNsex$</token>
				<token id="1.4">$[ ]IoNpatientID$</token>
			</line>
			<line>
				<token id="1.5">$[Acc: ]IoNaccessionNumber$</token>
			</line>
			<line>
				<token id="1.6">$IoNstudyDate$</token>
			</line>
		</block>

		<block hotspot="NE"
			   xpos="100" xunit="PERCENT"
               ypos="0" yunit="PERCENT"
	           justification="R">
			<name>Study/Series Information</name>
			<line>
				<token id="2.1">$IoNseriesDescription$</token>
			</line>
			<line>
				<token id="2.2">$IoNimageColumns$x$IoNimageLines$</token>
			</line>
			<line>
				<token id="2.4">$IoNseriesModality$</token>
			</line>
			<line>
				<token>$VarContrastAgentMark$$[  ]VarIsLossy$</token>
			</line>
			<line blank="1" />
			<line>
			    <token id="2.3">Mag: $VarZoomFactor%.2f$x</token>
			</line>
		</block>

		<block hotspot="SW"
			   xpos="0" xunit="PERCENT"
			   ypos="100" yunit="PERCENT"
			   justification="L">
			<name>Image Information</name>
			<line>
				<token id="3.1">$VarWindowLevels$</token>
			</line>
			<line>
				<token id="3.2">Im $VarImageNumber$/$VarNumberOfImages$</token>
				<token id="3.3">, #$VarDicomImageNumber$</token>
			</line>
		</block>

		<block hotspot="SE"
		       xpos="100" xunit="PERCENT"
               ypos="-16" yunit="PIXEL"
	           justification="R">
			<name>Hospital, Model</name>
			<line>
				<token id="4.4">$IoNimageComment$</token>
			</line>
			<line>
				<token id="4.3">$IoNstationName$</token>
			</line>
			<line>
				<token id="4.1">$IoNmodelName$</token>
			</line>
			<line>
				<token id="4.2">$IoNinstitutionName$</token>
			</line>
		</block>

		<block type="tag"
			   hotspot="SE"
	           xpos="100" xunit="PERCENT"
			   ypos="100" yunit="PERCENT">
			<name>Image Tag</name>
		</block>

		</image>

		<elt id="1.1" select="1">Patient name</elt>
		<elt id="1.2" select="1">Patient age</elt>
		<elt id="1.3" select="1">Patient sex</elt>
		<elt id="1.4" select="1">Patient ID</elt>
		<elt id="1.5" select="1">Accession Number</elt>
		<elt id="1.6" select="1">Study date</elt>
		<elt id="2.1" select="1">Series description</elt>
		<elt id="2.2" select="1">Image size</elt>
		<elt id="2.3" select="1">Zoom factor</elt>
		<elt id="2.4" select="1">Modality</elt>
		<elt id="3.1" select="1">Window level</elt>
		<elt id="3.2" select="1">Image number in series</elt>
		<elt id="3.3" select="1">DICOM image number</elt>
		<elt id="4.1" select="1">Model name</elt>
 		<elt id="4.2" select="1">Institution name</elt>
		<elt id="4.3" select="1">Station name</elt>
   		<elt id="4.4" select="1">Image comment</elt>
	</config>

	<config>
		<name>CT default</name>

		<image>

		<font charset="0" clipprecision="2" escapement="0"
			italic="0" orientation="0" outprecision="1"
			pitchandfamily="34" quality="1" strikeout="0" underline="0"
			facename="Arial"
			height="-12" weight="400"/>

		<block hotspot="NW"
			   xpos="0" xunit="PERCENT"
			   ypos="0" yunit="PERCENT"
			   justification="L">
			<name>Patient, Study Information</name>
			<line>
				<token id="1.1">$IoNfamilyName$  $IoNfirstName$</token>
			</line>
			<line>
				<token id="1.2">$VarPatientAge$</token>
				<token id="1.3">$[ ]IoNsex$</token>
				<token id="1.4">$[ ]IoNpatientID$</token>
			</line>
			<line>
				<token id="1.5">$[Acc: ]IoNaccessionNumber$</token>
			</line>
			<line>
				<token id="1.6">$IoNstudyDate$</token>
			</line>
		</block>

		<block hotspot="NE"
			   xpos="100" xunit="PERCENT"
               ypos="0" yunit="PERCENT"
	           justification="R">
			<name>Study/Series Information</name>
			<line>
				<token id="2.1">$IoNseriesDescription$</token>
			</line>
			<line>
				<token id="2.2">$IoNimageColumns$x$IoNimageLines$</token>
			</line>
			<line>
				<token>$VarContrastAgentMark$$[  ]VarIsLossy$</token>
			</line>
			<line blank="1" />
			<line>
			    <token id="2.3">Mag: $VarZoomFactor%.2f$x</token>
			</line>
		</block>

		<block hotspot="SW"
			   xpos="0" xunit="PERCENT"
			   ypos="100" yunit="PERCENT"
			   justification="L">
			<name>Image Information</name>
			<line>
			    <token id="3.4">$#IoNimageCTKvp%.1f[ kV]$</token>
			</line>
			<line>
				<token id="3.5">$IoNimageCTXrayTubeCurrent[ mA]$</token>
			</line>
			<line>
				<token id="3.6">$#IoNsliceThickness%.1f[ mm]$$#[ / ]VarSliceLocation$</token>
			</line>
			<line>
				<token id="3.1">$VarWindowLevels$</token>
			</line>
			<line>
				<token id="3.2">Im $VarImageNumber$/$VarNumberOfImages$</token>
				<token id="3.3">, #$VarDicomImageNumber$</token>
			</line>
		</block>

		<block hotspot="SE"
		       xpos="100" xunit="PERCENT"
               ypos="-16" yunit="PIXEL"
	           justification="R">
			<name>Hospital, Model</name>
			<line>
				<token id="4.4">$IoNimageComment$</token>
			</line>
			<line>
				<token id="4.3">$IoNstationName$</token>
			</line>
			<line>
				<token id="4.1">$IoNmodelName$</token>
			</line>
			<line>
				<token id="4.2">$IoNinstitutionName$</token>
			</line>
		</block>

		<block type="tag"
			   hotspot="SE"
	           xpos="100" xunit="PERCENT"
			   ypos="100" yunit="PERCENT">
			<name>Image Tag</name>
		</block>

		<block type="calliper" 
		       hotspot="E"
		       xpos="-40" xunit="PIXEL"
			   ypos="-110" yunit="PIXEL">
			<name>Calliper</name>
		</block>

		<block type="localizer" 
		       hotspot="SW"
		       xpos="0" xunit="PERCENT"
		       ypos="100" yunit="PERCENT"
		       showLocalizer="1"
		       showLocalizerPercentView="25"
		       showLocalizerBounds="0"
		       showLocalizerOrientation="1"
		       showLocalizerFrameNumber="1">
			<name>Localizer</name>
		</block>

		</image>

		<elt id="1.1" select="1">Patient name</elt>
		<elt id="1.2" select="1">Patient age</elt>
		<elt id="1.3" select="1">Patient sex</elt>
		<elt id="1.4" select="1">Patient ID</elt>
		<elt id="1.5" select="1">Accession Number</elt>
		<elt id="1.6" select="1">Study date</elt>
		<elt id="2.1" select="1">Series description</elt>
		<elt id="2.2" select="1">Image size</elt>
		<elt id="2.3" select="1">Zoom factor</elt>
		<elt id="3.1" select="1">Window level</elt>
		<elt id="3.2" select="1">Image number in series</elt>
		<elt id="3.3" select="1">DICOM image number</elt>
		<elt id="3.4" select="1">KVP</elt>
		<elt id="3.5" select="1">Tube current</elt>
		<elt id="3.6" select="1">Slice thickness and location</elt>
		<elt id="4.1" select="1">Model name</elt>
 		<elt id="4.2" select="1">Institution name</elt>
		<elt id="4.3" select="1">Station name</elt>
		<elt id="4.4" select="1">Image comment</elt>
   
	</config>

	<config>
		<name>CT (ACR Information)</name>

		<image>

		<font charset="0" clipprecision="2" escapement="0"
			italic="0" orientation="0" outprecision="1"
			pitchandfamily="34" quality="1" strikeout="0" underline="0"
			facename="Arial"
			height="-12" weight="400"/>

		<block hotspot="NW"
			   xpos="0" xunit="PERCENT"
			   ypos="0" yunit="PERCENT"
			   justification="L">
			<name>Patient, Study Information</name>
			<line>
				<token id="1.1">$IoNfamilyName$  $IoNfirstName$</token>
			</line>
			<line>
				<token id="1.2">$VarPatientAge$</token>
				<token id="1.3">$[ ]IoNsex$</token>
				<token id="1.4">$[ ]IoNpatientID$</token>
			</line>
			<line>
				<token id="1.5">$[Acc: ]IoNaccessionNumber$</token>
			</line>
			<line>
				<token id="1.6">$IoNstudyDate$</token>
			</line>
		</block>

		<block hotspot="NE"
			   xpos="100" xunit="PERCENT"
               ypos="0" yunit="PERCENT"
	           justification="R">
			<name>Study/Series Information</name>
			<line>
				<token id="2.1">$IoNseriesDescription$</token>
			</line>
			<line>
				<token id="2.2">$IoNimageColumns$x$IoNimageLines$</token>
			</line>
			<line>
				<token>$VarContrastAgentMark$$[  ]VarIsLossy$</token>
			</line>
			<line blank="1" />
			<line>
			    <token id="2.3">Mag: $VarZoomFactor%.2f$x</token>
			</line>
		
		</block>

		<block hotspot="SW"
			   xpos="0" xunit="PERCENT"
			   ypos="100" yunit="PERCENT"
			   justification="L">
			<name>Image Information</name>

			<line>
				<token id="ACR.CT.14">$[Series Number: ]IoNseriesNumber$</token>
			</line>
			
			<line>
				<token id="ACR.CT.6">$[Start Time: ]IoNstudyTime$</token>
			</line>

			<line>
				<token id="ACR.CT.24">$[Time of Day: ]IoNseriesTime$</token>
			</line>

			<line>
				<token id="ACR.CT.7">$[Tech's ID: ]IoNoperatorsName$</token>
			</line>
	
			<line>
				<token id="ACR.CT.12">$[Table feed rate: ]IoNimageCTTableFeedPerRotation$</token>
			</line>
	
			<line>
				<token id="ACR.CT.13">$[Scan Time: ]IoNacquisitionTime$</token>
			</line>
			
			<line>
				<token id="ACR.CT.13.1">$[Scan Duration: ]Tag00189073$</token>
			</line>
			
			<line>
				<token id="ACR.CT.22">$[Field of View: ]IoNimageCTReconstructionDiameter$</token>
			</line>

			<line>
				<token id="ACR.CT.25">$[Conv. Kernel: ]Tag00181210$</token>
			</line>
			
			<!-- Usually only one will be present:
				(0018, 9305) Revolution Time (The time in seconds of a complete revolution of the source 
				around the gantry orbit), and (0018, 1150) Exposure Time (Time of x-ray exposure in msec) -->
			<line>
				<token id="ACR.CT.26">$#[Rotation: ]Tag00189305[ ]$$#[Rotation : ]Tag00181150$</token>
			</line>
			
			<line>
			    <token id="3.4">$#IoNimageCTKvp%.1f[ kV]$</token>
			</line>
			<line>
